docs: Standardize the README
php-fig/http-server-handler pull request #5
Opened 2019-05-21 05:50 UTC by gnumoksha

What:
Standardizes the README file providing a common language and an implementation link.

Why:
There are differences between PSR's READMEs in regarding language and the lacking of implementations references. So I've updated all READMEs using the https://github.com/php-fig/http-factory as base.

2019-05-21 09:30 UTC, Jean85 approved these changes
LGTM :+1: Waiting for editor's review

2019-05-21 13:10 UTC, shadowhand requested changes

2019-05-21 13:10 UTC, shadowhand commented on README.md
> +HTTP Server Request Handlers
```suggestion
HTTP Server Request Handlers for Middleware
```

2019-05-21 13:10 UTC, shadowhand commented on README.md
> +You can find [implementations][implementation-url] and [installation instructions][package-url] for the specification on the packagist.
Same changes as https://github.com/php-fig/http-factory/pull/9 should be applied here.

2019-05-23 18:10 UTC, shadowhand requested changes

2019-05-23 18:10 UTC, shadowhand commented on README.md
> +==============
The length of this should match the line above, or it should be switched to `#`

2019-06-07 16:00 UTC, shadowhand approved these changes

2019-06-07 16:00 UTC, merged

2019-06-07 16:00 UTC, shadowhand commented
Thanks!